import type { Metadata } from "next";
import "./globals.css";
import PageHeader from "@/components/pageHeader";



export const metadata: Metadata = {
  title: {
    template: "%s | Finance App",
    default: "Finance App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="space-y-8">
          <div>{children}</div>
        </div>
        <footer className="mt-auto text-center py-8 dark:text-zinc-400 light:text-zinc-600">
          Copyright © 2025 by Mahdi Khorshidi
        </footer>
      </body>
    </html>
  );
}
