export const styles: Record<string, string> = {
    text: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    password: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    email: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    number: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    search: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    url: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    tel: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    date: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    time: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    datetime: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    "datetime-local": "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    month: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    week: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
    file: "block w-full text-sm text-gray-600 file:mr-4 file:py-2 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100 transition mb-2",
    checkbox: "rounded-md border-gray-300 text-blue-600 bg-white dark:bg-gray-950 dark:text-gray-500 shadow-sm focus:ring-2 focus:ring-blue-500 transition mr-2",
    radio: "rounded-full border-gray-300 text-blue-600 bg-white dark:bg-gray-950 dark:text-gray-500 shadow-sm focus:ring-2 focus:ring-blue-500 transition mr-2",
    range: "w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition",
    color: "w-12 h-12 p-0 border-0 rounded-lg shadow-md mb-2",
    hidden: "",
    submit: "px-6 py-2 rounded-lg bg-blue-600 text-white font-semibold shadow-md hover:bg-blue-700 transition mb-2",
    reset: "px-6 py-2 rounded-lg bg-gray-400 text-white font-semibold shadow-md hover:bg-gray-500 transition mb-2",
    button: "px-6 py-2 rounded-lg bg-green-600 text-white font-semibold shadow-md hover:bg-green-700 transition mb-2",
    image: "",
    default: "w-full rounded-lg shadow-md border border-gray-300 bg-white px-4 py-2 mb-2 focus:outline-none focus:ring-2 focus:ring-blue-500 transition dark:border-gray-700 dark:bg-gray-950",
};
